# Generated by Django 5.2.9 on 2025-12-16 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ARCHITECT', 'Arquiteto de Soluções (Risco & BPMN)'), ('DEV', 'Engenheiro Craftsman (TDD & Clean Code)'), ('QA', 'Auditor de Qualidade (Reviewer)')], max_length=20)),
                ('system_prompt', models.TextField(help_text='A persona e instruções base do agente.')),
                ('model_provider', models.CharField(default='gpt-4-turbo', help_text='Ex: gpt-4, claude-3-opus', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
