# Generated by Django 5.2.9 on 2025-12-16 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Diária')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('RENTED', 'Alugado'), ('MAINTENANCE', 'Em Manutenção')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
